// <auto-generated />
namespace CodeFirstMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddLastMet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLastMet));
        
        string IMigrationMetadata.Id
        {
            get { return "202004202248598_AddLastMet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
